### ISSUE TITLE
Cant repair Silent gear tools

### ISSUE THREAD

**Issue by AXJB01** [ValhelsiaTeam/Valhelsia#159] opened 2020-07-12 09:15 UTC
After I updated to the latest version of 1.15 pack, I can not repair my silent gear tools, even new ones I have made after the update.

**Comment by Vaelzan** [comment] 2020-07-12 10:51
Duplicate of https://github.com/ValhelsiaTeam/Valhelsia/issues/141 and https://github.com/ValhelsiaTeam/Valhelsia/issues/140

You can craft a dagger without a blueprint to make repair kits. You can also repair tools in an anvil or I think a grindstone.

**Closed by Vaelzan** 2020-07-12 10:51 UTC
