### ISSUE TITLE
Optine with shaders causingweird visual glitch when tool is used

### ISSUE THREAD

**Issue by sudo-make** [ValhelsiaTeam/Valhelsia#146] opened 2020-07-08 17:20 UTC
Optifine Version: 1.15.2 HD U G1 pre30
Velhelsia: 2.2.4

Not sure if issues relating to shaders and Optifine are allowed here, so sorry if it is not.
Whenever I use *any* shader, I get a weird bug that causes a visual glitch whenever I attempt to break a block using any tool (my hand works fine).
![InstantGif_2020 07 08-18 15](https://user-images.githubusercontent.com/20684751/86950050-85367980-c147-11ea-803d-378192cc6ce4.gif)

**Comment by sudo-make** [comment] 2020-07-08 17:41
UPDATE: Turned on "Showbuffer" in shader's settings. This is the result:

![InstantGif_2020 07 08-18 41](https://user-images.githubusercontent.com/20684751/86952281-a77dc680-c14a-11ea-9333-827533cb46ea.gif)

**Comment by Vaelzan** [comment] 2020-07-09 05:52
Duplicate of https://github.com/ValhelsiaTeam/Valhelsia/issues/129 which has the solution in the comments. In future, please try to get support via our Discord server, where we have a pinned post on this issue.

**Closed by Vaelzan** 2020-07-09 05:52 UTC
